version: '3.9'
services:
  mediamtx:
    image: bluenviron/mediamtx:1.20.1@sha256:1b029d11049be75630e9b73bb0d5f47b08a7db4eaee89a80bf8f53bc40e56414
    hostname: mediamtx
    container_name: mediamtx__mediamtx
    restart: unless-stopped

    ports:
      - 1935:1935
      - 554:8554

    volumes:
      - type: bind
        source: ./mediamtx.yml
        target: /mediamtx.yml
        read_only: true

    networks:
      - default
      
    deploy:
      resources:
        limits:
          memory: 1024m

  cloudflared:
    image: cloudflare/cloudflared:2026.8.2-amd64@sha256:de55830499e9adb1c580f7b5cbbdef86a3ff1715fb3ae6b3ff242f19de0afde8
    hostname: cloudflared
    container_name: mediamtx__cloudflared
    restart: unless-stopped

    environment:
      TUNNEL_METRICS: 0.0.0.0:9126
      TUNNEL_LOGFILE: /dev/stdout

    command: tunnel run --token ${TUNNEL_TOKEN}
    user: root

    networks:
      default:

    deploy:
      resources:
        limits:
          memory: 128m

networks:
  default:
    name: mediamtx__default
