version: '3.9'
services:
  mediamtx:
    image: bluenviron/mediamtx:1.17.1@sha256:9e39256d1ba35f0063700c6f62dd32e6db4592ddd9560d78f409ec451d79b1d8
    hostname: mediamtx
    container_name: mediamtx__mediamtx
    restart: unless-stopped

    ports:
      - 1935:1935
      - 554:8554

    volumes:
      - type: bind
        source: ./mediamtx.yml
        target: /mediamtx.yml
        read_only: true

    networks:
      - default
      
    deploy:
      resources:
        limits:
          memory: 1024m

  cloudflared:
    image: cloudflare/cloudflared:2026.3.0-amd64@sha256:64f4e9d6a867f71d89ae3318460bb3c604923b4af62b1bc9e2f74ee7486e3052
    hostname: cloudflared
    container_name: mediamtx__cloudflared
    restart: unless-stopped

    environment:
      TUNNEL_METRICS: 0.0.0.0:9126
      TUNNEL_LOGFILE: /dev/stdout

    command: tunnel run --token ${TUNNEL_TOKEN}
    user: root

    networks:
      default:

    deploy:
      resources:
        limits:
          memory: 128m

networks:
  default:
    name: mediamtx__default
