version: '3.9'
services:
  mediamtx:
    image: bluenviron/mediamtx:1.21.0@sha256:19fddade8d6110a3d718ac0045681fbeba344ae563a066205fe5929a87f7582f
    hostname: mediamtx
    container_name: mediamtx__mediamtx
    restart: unless-stopped

    ports:
      - 1935:1935
      - 554:8554

    volumes:
      - type: bind
        source: ./mediamtx.yml
        target: /mediamtx.yml
        read_only: true

    networks:
      - default
      
    deploy:
      resources:
        limits:
          memory: 1024m

  cloudflared:
    image: cloudflare/cloudflared:2026.9.1-amd64@sha256:d68fa057087c359c79a255570e891215877ce48aa48ba6f28aac90d8077acbc3
    hostname: cloudflared
    container_name: mediamtx__cloudflared
    restart: unless-stopped

    environment:
      TUNNEL_METRICS: 0.0.0.0:9126
      TUNNEL_LOGFILE: /dev/stdout

    command: tunnel run --token ${TUNNEL_TOKEN}
    user: root

    networks:
      default:

    deploy:
      resources:
        limits:
          memory: 128m

networks:
  default:
    name: mediamtx__default
